const path = require('path')
const projectRoot = __dirname

module.exports = {
  apps: [
    {
      name: 'mytgapp-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -H 0.0.0.0',
      cwd: projectRoot,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        HOSTNAME: '0.0.0.0',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_BOT_USERNAME: process.env.TELEGRAM_BOT_USERNAME,
        NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME,
        NEXTAUTH_URL: process.env.NEXTAUTH_URL,
        AUTH_URL: process.env.AUTH_URL,
        DATABASE_URL: process.env.DATABASE_URL,
        // Stripe configuration
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        STRIPE_MONTHLY_PRICE_ID: process.env.STRIPE_MONTHLY_PRICE_ID,
        SUBSCRIPTION_STRIPE_PRICE_ID: process.env.SUBSCRIPTION_STRIPE_PRICE_ID,
        STRIPE_REVENUE_SHARE_PRICE_ID: process.env.STRIPE_REVENUE_SHARE_PRICE_ID,
        MONTHLY_SUBSCRIPTION_PRICE: process.env.MONTHLY_SUBSCRIPTION_PRICE,
        // Other env vars will be loaded by Next.js from .env file automatically
      },
      error_file: './logs/mytgapp-web-error.log',
      out_file: './logs/mytgapp-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      instance_var: 'INSTANCE_ID',
    },
    {
      name: 'mytgapp-bot',
      script: 'node_modules/.bin/tsx',
      args: 'scripts/telegram-bot.ts',
      cwd: projectRoot,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_BOT_USERNAME: process.env.TELEGRAM_BOT_USERNAME,
        DATABASE_URL: process.env.DATABASE_URL,
      },
      error_file: './logs/mytgapp-bot-error.log',
      out_file: './logs/mytgapp-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      instance_var: 'INSTANCE_ID',
    },
  ],
};
