module.exports = {
  apps: [
    {
      name: 'mytgapp-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -H 0.0.0.0',
      cwd: process.cwd(),
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        HOSTNAME: '0.0.0.0',
      },
      error_file: './logs/mytgapp-web-error.log',
      out_file: './logs/mytgapp-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      instance_var: 'INSTANCE_ID',
    },
    {
      name: 'mytgapp-bot',
      script: 'node_modules/.bin/tsx',
      args: 'scripts/telegram-bot.ts',
      cwd: process.cwd(),
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/mytgapp-bot-error.log',
      out_file: './logs/mytgapp-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      instance_var: 'INSTANCE_ID',
    },
  ],
};
